Numpy Array operations

In [4]:
import numpy as np

In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Basic slicing ", arr[2:7])
print("Slicing with step ", arr[2:7:2])
print("Negative indexing", arr[-3])



Basic slicing  [3 4 5 6 7]
Slicing with step  [3 5 7]
Negative indexing 7


In [10]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Specific element ", arr_2d[1, 2])
print("Entire Row  ", arr_2d[1])
print("Entire Column ", arr_2d[:, 1])


Specific element  6
Entire Row   [4 5 6]
Entire Column  [2 5 8]


Sorting


In [11]:
unsorted = np.array([3, 7, 1, 9, 2])
print("sorted array ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 7, 1], [9, 2, 6], [5, 4, 8]])
print("2D sorted array by row", np.sort(arr_2d_unsorted, axis=1))  # Sort each row
print("2D sorted array by col", np.sort(arr_2d_unsorted, axis=0))  # Sort each column

sorted array  [1 2 3 7 9]
2D sorted array by row [[1 3 7]
 [2 6 9]
 [4 5 8]]
2D sorted array by col [[3 2 1]
 [5 4 6]
 [9 7 8]]


## Filter

In [12]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
even_number = numbers[numbers % 2 == 0]
print("Even numbers ", even_number)

Even numbers  [2 4 6 8]


Filter with mask

In [13]:
mask = numbers > 5
print("Numbers greater than 5", numbers[mask])


Numbers greater than 5 [6 7 8 9]


##Fancy indexing vs np.where()

In [14]:
indice = [0,4,5]
print("Fancy indexing ", numbers[indice])

where_result = np.where(numbers > 5)
print(where_result)
print("np.where() ", numbers[where_result])  # numbers greater than 5


Fancy indexing  [1 5 6]
(array([5, 6, 7, 8]),)
np.where()  [6 7 8 9]


In [15]:
condition_array = np.where(numbers >5, numbers*2, numbers)
print("Condition array ", condition_array)


Condition array  [ 1  2  3  4  5 12 14 16 18]


### adding and removing data

In [17]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print("Combined array ", combined)

Combined array  [1 2 3 4 5 6]


### array compatibility

In [22]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6 , 9])
c = np.array([7, 8, 9])

print("Compatible shapes", a.shape == b.shape) 

original = np.array([[1, 2], [4, 5]])
new_row = np.array([[7, 8]])
with_new_row = np.vstack((original, new_row))
print(original)
print("With new row ", with_new_row)

new_col = np.array([[10], [11], [12]])
with_new_col = np.hstack((with_new_row, new_col))
print("With new column ", with_new_col)


Compatible shapes False
[[1 2]
 [4 5]]
With new row  [[1 2]
 [4 5]
 [7 8]]
With new column  [[ 1  2 10]
 [ 4  5 11]
 [ 7  8 12]]


In [23]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print("Array after deletion: ", deleted)


Array after deletion:  [1 2 4 5]
