Numpy Array operations

In [1]:
import numpy as np

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Basic slicing ", arr[2:7])
print("Slicing with step ", arr[2:7:2])
print("Negative indexing", arr[-3])



Basic slicing  [3 4 5 6 7]
Slicing with step  [3 5 7]
Negative indexing 7


In [8]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Specific element ", arr_2d[1, 2])
print("Entire Row  ", arr_2d[1])
print("Entire Column ", arr_2d[:, 1])


Specific element  6
Entire Row   [4 5 6]
Entire Column  [2 5 8]


Sorting


In [ ]:
unsorted = np.array([3, 7, 1, 9, 2])
print("sorted array ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 7, 1], [9, 2, 6], [5, 4, 8]])
print("2D sorted array by row", np.sort(arr_2d_unsorted, axis=1))  # Sort each row
print("2D sorted array by col", np.sort(arr_2d_unsorted, axis=0))  # Sort each column

sorted array  [1 2 3 7 9]
2D sorted array by col [[1 3 7]
 [2 6 9]
 [4 5 8]]
2D sorted array by row [[3 2 1]
 [5 4 6]
 [9 7 8]]


## Filter

In [20]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
even_number = numbers[numbers % 2 == 0]
print("Even numbers ", even_number)

Even numbers  [2 4 6 8]


Filter with mask

In [21]:
mask = numbers > 5
print("Numbers greater than 5", numbers[mask])


Numbers greater than 5 [6 7 8 9]


##Fancy indexing vs np.where()

In [23]:
indice = [0,4,5]
print("Fancy indexing ", numbers[indice])

where_result = np.where(numbers > 5)
print(where_result)
print("np.where() ", numbers[where_result])  # numbers greater than 5


Fancy indexing  [1 5 6]
(array([5, 6, 7, 8]),)
np.where()  [6 7 8 9]


In [ ]:
condition_array = np.where(numbers >5, numbers *2, numbers)
print("Condition array ", condition_array)


Condition array  (array([5, 6, 7, 8]),)
