In [2]:
import numpy as np

creating arrays from list

In [5]:
arr_id = np.array([1, 2, 3, 4, 5])
print(arr_id)

arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### List vs numpy array

In [7]:
py_list = [1, 2, 3, 4, 5]
print("python list multiplication ", py_list *2)

np_array = np.array([1, 2, 3, 4, 5]) # element wise multiplication
print("Python array multiplication ", np_array *2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) *2
print("\n Numpy operation time: ", time.time() - start)



python list multiplication  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Python array multiplication  [ 2  4  6  8 10]

 List operation time:  0.144944429397583

 Numpy operation time:  0.009377002716064453


creating array from scratch

In [ ]:
zeros = np.zeros((3, 4))
print("\n Array of zeros: \n", zeros)

ones = np.ones((2,3))
print("\n Array of ones: \n", ones)

full = np.full((2,2),7)
print("\n Array of full: \n", full)

random = np.random.random((2,3))
print("\n Array of random: \n", random)

sequence = np.arange(0, 10, 2)
print("\n Array of sequence: \n", sequence)




 Array of zeros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 Array of ones: 
 [[1. 1. 1.]
 [1. 1. 1.]]

 Array of full: 
 [[7 7]
 [7 7]]

 Array of random: 
 [[0.64395591 0.89419122 0.37637723]
 [0.60976548 0.62094001 0.56137889]]

 Array of sequence: 
 [0 2 4 6 8]


### Vector , Matrix and Tensor

In [13]:
vector = np.array([1, 2, 3])
print("\n Vector: \n", vector)

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n Matrix: \n", matrix)

tensor = np.array([[[1, 2], [3,4]],
                   [[5, 6], [7, 8]]])
print("\n Tensor: \n", tensor)



 Vector: 
 [1 2 3]

 Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array properties

In [20]:
arr = np.array([[1, 2,3],
               [4, 5, 6]])
print("shape" , arr.shape)
print("dimension", arr.ndim)
print("size", arr.size)
print("data type", arr.dtype)

shape (2, 3)
dimension 2
size 6
data type int64


Array Reshaping 

In [27]:
arr = np.arange(12)
print("Original array:", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array ", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n Raveled array ", raveled)

#Transpose
transposed = reshaped.T
print("/n Transposed array ", transposed)


Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
/n Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
